/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: 'autogenerated-index'},
    {
      type: 'category',
      label: 'API REST (développeurs)',
      collapsible:false,
      items: [
        'api-rest',
        {
          type: 'link',
          label: 'Points de terminaison', // Le libellé du lien
          href: 'https://opencomp.github.io/docv2/api/', // L'URL externe
        },
      ],
    },
    
  ],
};
